# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/copperthief/catalyst

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/copperthief/catalyst

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/copperthief/catalyst/CMakeFiles /home/copperthief/catalyst//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/copperthief/catalyst/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named catalyst

# Build rule for target.
catalyst: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 catalyst
.PHONY : catalyst

# fast build rule for target.
catalyst/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/build
.PHONY : catalyst/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/glfw-3.3.7/CMakeFiles/uninstall.dir/build.make lib/glfw/glfw-3.3.7/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/glfw-3.3.7/src/CMakeFiles/update_mappings.dir/build.make lib/glfw/glfw-3.3.7/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/glfw-3.3.7/src/CMakeFiles/glfw.dir/build.make lib/glfw/glfw-3.3.7/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) $(MAKESILENT) -f lib/glew/glew-2.2.0/build/cmake/CMakeFiles/glew.dir/build.make lib/glew/glew-2.2.0/build/cmake/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named glew_s

# Build rule for target.
glew_s: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glew_s
.PHONY : glew_s

# fast build rule for target.
glew_s/fast:
	$(MAKE) $(MAKESILENT) -f lib/glew/glew-2.2.0/build/cmake/CMakeFiles/glew_s.dir/build.make lib/glew/glew-2.2.0/build/cmake/CMakeFiles/glew_s.dir/build
.PHONY : glew_s/fast

#=============================================================================
# Target rules for targets named glewinfo

# Build rule for target.
glewinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glewinfo
.PHONY : glewinfo

# fast build rule for target.
glewinfo/fast:
	$(MAKE) $(MAKESILENT) -f lib/glew/glew-2.2.0/build/cmake/CMakeFiles/glewinfo.dir/build.make lib/glew/glew-2.2.0/build/cmake/CMakeFiles/glewinfo.dir/build
.PHONY : glewinfo/fast

#=============================================================================
# Target rules for targets named visualinfo

# Build rule for target.
visualinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 visualinfo
.PHONY : visualinfo

# fast build rule for target.
visualinfo/fast:
	$(MAKE) $(MAKESILENT) -f lib/glew/glew-2.2.0/build/cmake/CMakeFiles/visualinfo.dir/build.make lib/glew/glew-2.2.0/build/cmake/CMakeFiles/visualinfo.dir/build
.PHONY : visualinfo/fast

src/AttributeOrder.o: src/AttributeOrder.cpp.o
.PHONY : src/AttributeOrder.o

# target to build an object file
src/AttributeOrder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/AttributeOrder.cpp.o
.PHONY : src/AttributeOrder.cpp.o

src/AttributeOrder.i: src/AttributeOrder.cpp.i
.PHONY : src/AttributeOrder.i

# target to preprocess a source file
src/AttributeOrder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/AttributeOrder.cpp.i
.PHONY : src/AttributeOrder.cpp.i

src/AttributeOrder.s: src/AttributeOrder.cpp.s
.PHONY : src/AttributeOrder.s

# target to generate assembly for a file
src/AttributeOrder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/AttributeOrder.cpp.s
.PHONY : src/AttributeOrder.cpp.s

src/Catalyst.o: src/Catalyst.cpp.o
.PHONY : src/Catalyst.o

# target to build an object file
src/Catalyst.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Catalyst.cpp.o
.PHONY : src/Catalyst.cpp.o

src/Catalyst.i: src/Catalyst.cpp.i
.PHONY : src/Catalyst.i

# target to preprocess a source file
src/Catalyst.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Catalyst.cpp.i
.PHONY : src/Catalyst.cpp.i

src/Catalyst.s: src/Catalyst.cpp.s
.PHONY : src/Catalyst.s

# target to generate assembly for a file
src/Catalyst.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Catalyst.cpp.s
.PHONY : src/Catalyst.cpp.s

src/IndexBuffer.o: src/IndexBuffer.cpp.o
.PHONY : src/IndexBuffer.o

# target to build an object file
src/IndexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/IndexBuffer.cpp.o
.PHONY : src/IndexBuffer.cpp.o

src/IndexBuffer.i: src/IndexBuffer.cpp.i
.PHONY : src/IndexBuffer.i

# target to preprocess a source file
src/IndexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/IndexBuffer.cpp.i
.PHONY : src/IndexBuffer.cpp.i

src/IndexBuffer.s: src/IndexBuffer.cpp.s
.PHONY : src/IndexBuffer.s

# target to generate assembly for a file
src/IndexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/IndexBuffer.cpp.s
.PHONY : src/IndexBuffer.cpp.s

src/InputHandler.o: src/InputHandler.cpp.o
.PHONY : src/InputHandler.o

# target to build an object file
src/InputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/InputHandler.cpp.o
.PHONY : src/InputHandler.cpp.o

src/InputHandler.i: src/InputHandler.cpp.i
.PHONY : src/InputHandler.i

# target to preprocess a source file
src/InputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/InputHandler.cpp.i
.PHONY : src/InputHandler.cpp.i

src/InputHandler.s: src/InputHandler.cpp.s
.PHONY : src/InputHandler.s

# target to generate assembly for a file
src/InputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/InputHandler.cpp.s
.PHONY : src/InputHandler.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/VertexArray.o: src/VertexArray.cpp.o
.PHONY : src/VertexArray.o

# target to build an object file
src/VertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/VertexArray.cpp.o
.PHONY : src/VertexArray.cpp.o

src/VertexArray.i: src/VertexArray.cpp.i
.PHONY : src/VertexArray.i

# target to preprocess a source file
src/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/VertexArray.cpp.i
.PHONY : src/VertexArray.cpp.i

src/VertexArray.s: src/VertexArray.cpp.s
.PHONY : src/VertexArray.s

# target to generate assembly for a file
src/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/VertexArray.cpp.s
.PHONY : src/VertexArray.cpp.s

src/VertexBuffer.o: src/VertexBuffer.cpp.o
.PHONY : src/VertexBuffer.o

# target to build an object file
src/VertexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/VertexBuffer.cpp.o
.PHONY : src/VertexBuffer.cpp.o

src/VertexBuffer.i: src/VertexBuffer.cpp.i
.PHONY : src/VertexBuffer.i

# target to preprocess a source file
src/VertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/VertexBuffer.cpp.i
.PHONY : src/VertexBuffer.cpp.i

src/VertexBuffer.s: src/VertexBuffer.cpp.s
.PHONY : src/VertexBuffer.s

# target to generate assembly for a file
src/VertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/VertexBuffer.cpp.s
.PHONY : src/VertexBuffer.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catalyst.dir/build.make CMakeFiles/catalyst.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... catalyst"
	@echo "... glew"
	@echo "... glew_s"
	@echo "... glewinfo"
	@echo "... glfw"
	@echo "... visualinfo"
	@echo "... src/AttributeOrder.o"
	@echo "... src/AttributeOrder.i"
	@echo "... src/AttributeOrder.s"
	@echo "... src/Catalyst.o"
	@echo "... src/Catalyst.i"
	@echo "... src/Catalyst.s"
	@echo "... src/IndexBuffer.o"
	@echo "... src/IndexBuffer.i"
	@echo "... src/IndexBuffer.s"
	@echo "... src/InputHandler.o"
	@echo "... src/InputHandler.i"
	@echo "... src/InputHandler.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/VertexArray.o"
	@echo "... src/VertexArray.i"
	@echo "... src/VertexArray.s"
	@echo "... src/VertexBuffer.o"
	@echo "... src/VertexBuffer.i"
	@echo "... src/VertexBuffer.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

